services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: devel
    volumes:
      - local_pgdata:/var/lib/postgresql/data
volumes:
  local_pgdata:
